- name: Deploy and configure nginx on Ubuntu
  hosts: linux-servers
  become: yes
  vars:
    webserver_port: 8080
    app_path: /var/www/myapp
    server_name: "ubuntu-server"

  roles:
    - nginx_configure
