events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    
    # Настройки для логов
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    server {
        listen 8080;
        server_name localhost;
        
        root /app/static;
        
        location / {
            index index.html;
            try_files $uri $uri/ =404;
        }
        
        # Автоматическое определение типа файлов
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|json)$ {
            expires 1d;
            add_header Cache-Control "public, immutable";
        }
    }
}
